### ISSUE TITLE
Can't activate if used with «WooCommerce PostFinance Checkout»

### ISSUE THREAD

**Issue by eightam** [wallee-payment/woocommerce-subscription#1]
I'm getting an error if I try to activate with «WooCommerce PostFinance Checkout». According to Postfinance Support this should work but the plugin activation fails saying that "Woocommerce walleee 1.2.12+" should be active.

![CleanShot 2022-06-27 at 10 59 48 2](https://user-images.githubusercontent.com/2012717/175904601-d7aebd29-bc26-40a1-8868-9b35810d76ef.png)

**Comment by sauliususoniswallee** [comment]
hello, @eightam thanks for the feedback, we will investigate this internally with development team

**Comment by sauliususoniswallee** [comment]
@eightam we believe the issue is in local set up, please do the following:
- uninstall the Postfinance plugin
- install the Wallee plugin (from wordpress marketplace: https://wordpress.org/plugins/woo-wallee/ ) 
- save your postfinance credentials on the wallee plugin 

please let us know if issue persists?
